# Generated by Django 4.1.3 on 2022-11-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazar', models.CharField(max_length=50, verbose_name='yazar')),
                ('baslik', models.CharField(max_length=50, verbose_name='baslik')),
                ('aciklama', models.CharField(max_length=100)),
                ('metin', models.CharField(max_length=150)),
                ('yayimlanma_tarihi', models.DateField(auto_now=True)),
                ('yaratilma_tahrihi', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
